import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import logo from "../../public/images/logo.png";

export const DHBranding = () => {
  return (
    <div className="text-white">
      <h1 className="font-montserrat font-bold text-4xl md:text-6xl">
        Delta<span className="font-normal">Hacks</span> IX
      </h1>
      <h2 className="font-montserrat text-sm md:text-xl">
        January 13-15 | McMaster University
      </h2>
    </div>
  );
};

const Login: NextPage = () => {
  const [dark, setDark] = useState<boolean>();

  useEffect(() => {
    const currentTheme = window.matchMedia(
      "(prefers-color-scheme: dark)"
    ).matches;
    setDark(currentTheme);
    window
      .matchMedia("(prefers-color-scheme: dark)")
      .addEventListener("change", (event) => {
        const colorScheme = event.matches ? true : false;
        setDark(colorScheme);
      });
  }, []);

  return (
    <>
      <Head>
        <title>DH9 Login Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* dark / light mode*/}
      <div
        className={`bg-[#272727] flex ${dark && "dark"} w-full h-full`}
        data-theme={dark ? "dark" : "light"}
      >
        <div className="bg-[#171717] relative overflow-hidden w-full md:w-1/2 h-full">
          <div
            className="absolute inset-0 -rotate-12 w-[200%] h-[200%] -top-[50%] -left-[50%] animate-slow-bg"
            style={{
              maskImage: "url(images/bg.png)",
              WebkitMaskImage: "url(images/bg.png)",
              background:
                "linear-gradient(#1C1C1C 0%, #1C1C1C 40%, #2e2e2e 50%, #1C1C1C 60%, #1C1C1C 100%)",
              backgroundSize: "200% 200%",
            }}
          ></div>
          <div className="absolute z-10 p-3 bottom-0 md:relative md:-translate-x-1/2 md:-translate-y-1/2 md:top-1/2 md:left-1/2 md:w-fit">
            <div className="flex gap-4 items-center">
              <div className="aspect-square w-20 md:w-40 hidden md:block">
                <Image
                  src={logo}
                  alt="DeltaHacks logo"
                  layout="responsive"
                ></Image>
              </div>
              <DHBranding />
            </div>
          </div>
        </div>
        <div className="md:px-32 absolute top-1/2 left-1/2 min-w-[85%] md:min-w-[40vw] -translate-x-1/2 -translate-y-1/2 md:left-3/4 ">
          <h2 className="mb-4 text-2xl font-bold text-black dark:text-white">
            Login
          </h2>
          <form className="w-full form-control md:pt-2 gap-3">
            <label className="label">
              <span className="label-text">Email</span>
            </label>
            <input
              type="email"
              placeholder="Email"
              className="w-full input input-bordered dark:bg-zinc-800"
            />
            <label className="label">
              <span className="label-text-alt">Password</span>
            </label>
            <input
              type="password"
              placeholder="Password"
              className="w-full input input-bordered dark:bg-zinc-800"
            />
            <button className="w-full mt-6 normal-case btn btn-primary">
              Login
            </button>
          </form>
        </div>
      </div>
    </>
  );
};

export default Login;
