import type { NextPage } from "next";
import Link from "next/link"
import Head from "next/head";
import { useState } from "react";


const Login: NextPage = () => {
    const [dark, setDark] = useState<boolean>(true);

    return (
    <>
      <Head>
        <title>DH9 Login Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`flex min-h-screen ${dark && "dark"}`}
        data-theme={dark ? "dark" : "light"}
      >
        <div className="bg-[#171717] flex-1 relative overflow-hidden">
          <div
            className="absolute inset-0 -rotate-12 w-[200%] h-[200%] -top-[50%] -left-[50%] animate-slow-bg"
            style={{
              maskImage: "url(images/bg.png)",
              WebkitMaskImage: "url(images/bg.png)",
              background:
                "linear-gradient(#1C1C1C 0%, #1C1C1C 40%, #2e2e2e 50%, #1C1C1C 60%, #1C1C1C 100%)",
              backgroundSize: "200% 200%",
            }}
          ></div>

          <img
            draggable="false"
            src="images/leftp.png"
            alt="deltahacks 9 logo"
            className="absolute -translate-x-1/2 -translate-y-1/2 lg:p-24 md:p-16 top-1/2 left-1/2"
          />
        </div>
        <div className="relative bg-white dark:bg-[#1F1F1F] flex-1">
          <div className="relative flex justify-between w-full p-4 pl-8">
            <button type="button" onClick={() => dark ? setDark(false) : setDark(true)}>
              <img src={dark ? "images/bxs_moon.svg" : "images/bxs_sun.svg"} alt="" />
            </button>
            <nav className="flex items-center justify-end gap-8">
              <a
                href="https://deltahacks.com"
                className="text-black dark:text-white"
              >
                Home{" "}
              </a>
              <Link href={"/SignUp"}>
                <button className="normal-case btn btn-primary bg-indigo-600 hover:bg-indigo-700 rounded-lg text-white text-sm py-3 px-4">
                    Sign Up
                </button>
              </Link>
              
            </nav>
          </div>
          <div className="absolute w-full px-8 -translate-x-1/2 -translate-y-1/2 lg:w-72 lg:p-0 md:px-20 left-1/2 top-1/2 ">
            <h2 className="mb-4 text-2xl font-inter font-bold text-black dark:text-white">
              Log In
            </h2>
            <form className="w-full form-control">
              <label className="label">
                <span className="label-text text-sm text-black dark:text-white">Email</span>
              </label>
              <input
                type="email"
                placeholder="Email"
                className="w-full input input-bordered dark:bg-zinc-800 p-4 my-2 rounded-lg text-black dark:text-white text-xs"
              />
              <label className="label">
                <span className="label-text-alt text-sm text-black dark:text-white">Password</span>
              </label>
              <input
                type="password"
                placeholder="Password"
                className="w-full input input-bordered dark:bg-zinc-800 p-4 mt-2 rounded-lg text-black dark:text-white text-xs"
              />
              <button className="w-full mt-6 py-4 normal-case btn btn-primary bg-indigo-600 hover:bg-indigo-700 rounded-lg text-white text-sm">
                Log In
              </button>
              <div className="font-inter text-sm font-normal mt-2 text-black dark:text-white">New? <Link href={"/SignUp"}><a href=""><strong>Sign Up</strong></a></Link> here</div>
              <div className="font-inter text-xs font-normal mt-2 text-black dark:text-white"><Link href={"/ForgotPassword"}>Forgot Password?</Link></div>
            </form>
          </div>
        </div>
      </div>
    </>

    //     <>
    //     <Head>
    //     <title>DH9 Login</title>
    //     <meta name="description" content="Generated by create-t3-app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //    <div className="grid grid-cols-2 divide-x">
    //     <div className="min-h-screen bg-black flex flex-col justify-center">
    //         <div className="flex flex-row justify-center">
    //             <div className="flex flex-col justify-center w-44 h-36 pr-4">
    //                 <img src="/images/logo.png" ></img>
    //             </div>
    //             <div className="flex flex-col justify-center">
    //                 <div className="font-montserrat text-white non-italic font-normal text-5xl"><strong>Delta</strong>Hacks<strong>IX</strong></div>
    //                 <div className="font-montserrat font-normal non-italic text-white text-lg">January 13-15 | McMaster University</div>
    //             </div>
    //         </div>
    //     </div>
    //     <div className=" bg-white flex flex-col">
    //         <div className="flex flex-row items-start justify-between mt-4">
    //             <div>icon</div>
    //             <div className="flex flex-row justify-center items-center">
    //                 <div className="font-inter text-sm font-bold pr-5"><a href="https://www.deltahacks.com/">Home</a></div>
    //                 <div className="mr-4">
    //                     <Link href={"/SignUp"}>
    //                         <button className="px-5 py-3 bg-indigo-600 hover:bg-indigo-700 rounded-lg text-white text-sm">Sign Up</button>
    //                     </Link>
    //                 </div>
    //             </div>
    //         </div>
    //         <div className="h-full flex flex-col items-center justify-center mb-10">
    //             <div className="w-80">
    //                 <div className="font-inter text-xl font-bold non-italic leading-6">Log In</div>
    //             </div>
    //             <div className="w-80 h-60 mt-6 ml-2">
    //                 <form action="" className="space-y-4">
    //                     <div>
    //                         <label className="text-sm font-inter font-normal">Email</label>
    //                         <input type="text" placeholder="Email" className="w-full p-4 border border-gray-200 border-double rounded-lg mt-2"></input>
    //                     </div>
    //                     <div>
    //                         <label className="text-sm font-inter font-normal ml-2">Password</label>
    //                         <input type="password" placeholder="Password" className="w-full p-4 border border-gray-200 border-double rounded-lg mt-2"></input>
    //                     </div>
    //                     <div>
    //                         <button className="w-full py-4 bg-indigo-600 hover:bg-indigo-700 rounded-lg text-white text-sm mt-2">Log In</button>
    //                     </div>
    //                     <div className="font-inter text-sm font-normal">New? <Link href={"/SignUp"}><a href=""><strong>Sign Up</strong></a></Link> here</div>
    //                 </form>
    //             </div>
    //         </div>
    //     </div>
    //    </div>
    //    </>
    )
}

export default Login;