import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Background from "../components/background";

import SocialButtons from "../components/SocialButtons";

const PostRegistration: NextPage = () => {
    return (
        <>
            <Head>
                <title>DH9 Post-Registration Page</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter&family=Montserrat&display=swap"
                    rel="stylesheet"
                />
            </Head>

            <div className="drawer drawer-end">
                <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
                <div className="drawer-content flex flex-col">
                    {/* <!-- Navbar --> */}
                    <div className="mx-9 mt-5 flex flex-row items-center justify-between md:mx-10 md:mt-8">
                        <div className="flex flex-row items-center justify-between">
                            <a className="mr-5" href="#">
                                <img
                                    className="inline-block h-10 w-12 md:h-16 md:w-20"
                                    src="logo.svg"
                                />
                            </a>

                            <div className="font-main hidden md:inline-block">
                                <h1 className="text-2xl">
                                    <strong>Delta</strong>Hacks <strong>IX</strong>
                                </h1>
                                <p className="text-xs">January 13-15 | McMaster University</p>
                            </div>

                            <div className="font-sub ml-5 hidden md:flex">
                                <a className="mx-2 text-base font-bold" href="#">
                                    Dashboard
                                </a>

                                <a className="mx-2 text-base font-bold" href="#">
                                    Calendar
                                </a>
                            </div>
                        </div>

                        <div className="flex items-center">
                            <button className="mx-2">
                                <img
                                    className="hidden h-5 w-5 md:inline-block"
                                    src="dark-toggle.svg"
                                />
                            </button>

                            <a className="font-sub mx-2 hidden text-sm lg:inline-block">
                                Logged in as <strong className="font-bold"> Username</strong>
                            </a>

                            <button className="font-sub mx-2 hidden rounded bg-[#4F14EE] py-2.5 px-5 text-sm font-bold md:inline-block md:px-7">
                                Sign out
                            </button>
                        </div>

                        <div className="flex-none md:hidden">
                            <label htmlFor="my-drawer-3" className="btn btn-ghost btn-square">
                                <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    fill="none"
                                    viewBox="0 0 24 24"
                                    className="inline-block h-6 w-6 stroke-current"
                                >
                                    <path
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth="2"
                                        d="M4 6h16M4 12h16M4 18h16"
                                    ></path>
                                </svg>
                            </label>
                        </div>
                    </div>

                    <Background />
                    <div className="font-main mt-24 sm:mt-28">
                        <main className="mt-8 ml-8 mr-6 flex flex-col md:ml-20 md:mt-16 md:justify-between">
                            <div className="w-11/12 md:w-9/12">
                                <h1 className="text-left text-3xl font-semibold leading-tight text-white md:text-5xl">
                                    Hi {"{"}username{"}"},
                                    <br />we have received your application.
                                </h1>
                                <p className="text-neutal-500 mt-8 text-left text-xl font-normal md:text-3xl md:leading-10">
                                    You should hear back from us soon
                                </p>
                            </div>
                        </main>
                    </div>
                </div>
                <div className="drawer-side md:hidden">
                    <label
                        htmlFor="my-drawer-3"
                        className="drawer-overlay md:hidden"
                    ></label>
                    <div className="menu h-full w-80 flex-row content-between overflow-y-auto bg-[#1F1F1F] p-4 md:hidden">
                        <ul className="w-full">
                            {/* <!-- Sidebar content here --> */}
                            <li>
                                <a className="mx-2 my-2 text-base font-bold" href="#">
                                    Dashboard
                                </a>
                            </li>
                            <li>
                                <a className="mx-2 my-2 text-base font-bold" href="#">
                                    Calendar
                                </a>
                            </li>
                        </ul>
                        <div className="mx-1 mb-2 flex w-full items-center justify-between">
                            <div>
                                <button className="mx-2 mt-2">
                                    <img className="h-5 w-5" src="dark-toggle.svg" />
                                </button>
                            </div>
                            <div>
                                <a className="font-sub mx-2.5 text-sm">
                                    Hi, <strong className="font-bold"> Username</strong>
                                </a>
                                <button className=" font-sub rounded bg-[#4F14EE] py-2.5 px-2.5 text-sm font-bold">
                                    Sign out
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
};

export default PostRegistration;
