import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

const SignUp: NextPage = () => {
  const [dark, setDark] = useState<boolean>(true);

  return (
    <>
      <Head>
        <title>DH9 Sign Up Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`flex min-h-screen ${dark && "dark"}`}
        data-theme={dark ? "dark" : "light"}
      >
        <div className="bg-[#171717] flex-1 relative overflow-hidden">
          <div
            className="absolute inset-0 -rotate-12 w-[200%] h-[200%] -top-[50%] -left-[50%] animate-slow-bg"
            style={{
              maskImage: "url(images/bg.png)",
              WebkitMaskImage: "url(images/bg.png)",
              background:
                "linear-gradient(#1C1C1C 0%, #1C1C1C 40%, #2e2e2e 50%, #1C1C1C 60%, #1C1C1C 100%)",
              backgroundSize: "200% 200%",
            }}
          ></div>

          <img
            draggable="false"
            src="images/leftp.png"
            alt="deltahacks 9 logo"
            className="absolute -translate-x-1/2 -translate-y-1/2 lg:p-24 md:p-16 top-1/2 left-1/2"
          />
        </div>
        <div className="relative bg-white dark:bg-[#1F1F1F] flex-1">
          <div className="relative flex justify-between w-full p-4 pl-8">
            <button
              type="button"
              onClick={() => (dark ? setDark(false) : setDark(true))}
            >
              <img
                src={dark ? "images/bxs_moon.svg" : "images/bxs_sun.svg"}
                alt=""
              />
            </button>
            <nav className="flex items-center justify-end gap-8">
              <a
                href="https://deltahacks.com"
                className="text-black dark:text-white"
              >
                Home{" "}
              </a>
              <Link href={"/Login"}>
                <button className="normal-case btn btn-primary bg-indigo-600 hover:bg-indigo-700 rounded-lg text-white text-sm py-3 px-4">
                  Log In
                </button>
              </Link>
            </nav>
          </div>
          <div className="absolute w-full px-8 -translate-x-1/2 -translate-y-1/2 lg:w-72 lg:p-0 md:px-20 left-1/2 top-1/2 mt-6">
            <h2 className="mb-4 text-2xl font-inter font-bold text-black dark:text-white">
              Sign Up
            </h2>
            <form className="w-full form-control">
              <label className="label">
                <span className="label-text text-sm text-black dark:text-white">
                  First Name
                </span>
              </label>
              <input
                type="email"
                placeholder="First Name"
                className="w-full input input-bordered dark:bg-zinc-800 p-4 my-2 rounded-lg text-black dark:text-white text-xs"
              />
              <label className="label">
                <span className="label-text text-sm text-black dark:text-white">
                  Last Name
                </span>
              </label>
              <input
                type="email"
                placeholder="Last Name"
                className="w-full input input-bordered dark:bg-zinc-800 p-4 my-2 rounded-lg text-black dark:text-white text-xs"
              />
              <label className="label">
                <span className="label-text text-sm text-black dark:text-white">
                  Email
                </span>
              </label>
              <input
                type="email"
                placeholder="Email"
                className="w-full input input-bordered dark:bg-zinc-800 p-4 my-2 rounded-lg text-black dark:text-white text-xs"
              />
              <label className="label">
                <span className="label-text-alt text-sm text-black dark:text-white">
                  Password
                </span>
              </label>
              <input
                type="password"
                placeholder="Password"
                className="w-full input input-bordered dark:bg-zinc-800 p-4 mt-2 rounded-lg text-black dark:text-white text-xs"
              />
              <button className="w-full mt-6 py-4 normal-case btn btn-primary bg-indigo-600 hover:bg-indigo-700 rounded-lg text-white text-sm">
                Sign Up
              </button>
              <div className="font-inter text-sm font-normal mt-2 text-black dark:text-white">
                Already have an account?{" "}
                <Link href={"/Login"}>
                  <a href="">
                    <strong>Log In</strong>
                  </a>
                </Link>{" "}
                here
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default SignUp;
