import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import NavBar from "../components/NavBar";
import Background from "../components/background";
import SocialButtons from "../components/SocialButtons";

const Welcome: NextPage = () => {
  return (
    <>
      <Head>
        <title>DH9 Welcome Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative min-h-screen h-full w-full overflow-x-hidden font-montserrat">
        <div className="absolute h-full w-full overflow-hidden bg-[#171717] inset-0 -z-10">
          <div
            className="absolute inset-0 -top-[50%] -left-[50%] h-[200%] w-[200%] -rotate-12 animate-slow-bg"
            style={{
              maskImage: "url(images/bg.png)",
              WebkitMaskImage: "url(images/bg.png)",
              background:
                "linear-gradient(#1C1C1C 0%, #1C1C1C 40%, #2e2e2e 50%, #1C1C1C 60%, #1C1C1C 100%)",
              backgroundSize: "200% 200%",
            }}
          ></div>
        </div>
        <NavBar />
        {/* <Background /> */}
        <main className="px-7 py-14 sm:px-14 md:absolute md:w-10/12 md:pb-3 lg:pl-20 2xl:w-8/12 2xl:pt-20">
          <div className="text-2xl font-semibold leading-tight text-white sm:text-3xl lg:text-5xl 2xl:text-6xl">
            A weekend worth hacking,
            <br />@ DeltaHacks 9
          </div>
          <div className="pt-6 text-xl font-normal text-[#737373] sm:text-2xl lg:pt-8 lg:text-3xl lg:leading-tight 2xl:pt-10 2xl:text-4xl">
            At DeltaHacks, we believe change comes from dreaming big. Each year
            we enable over 800 students from across North America, working hard
            over 36 hours, to bring their big ideas to life. Unleash your
            creativity and make something great, we{"'"}ll handle the rest! Make
            big ideas a reality at DeltaHacks 9!
          </div>
          <div className="pt-6 text-xl font-normal text-[#737373] sm:text-2xl lg:pt-8 lg:text-3xl lg:leading-tight 2xl:pt-10 2xl:text-4xl">
            If you have any questions, you can <br />
            reach us at{" "}
            <a href="mailto: hello@deltahacks.com" className="text-sky-400">
              hello@deltahacks.com
            </a>
          </div>
          <div className="flex flex-col gap-3 pt-6 md:flex-row lg:pt-8 2xl:pt-10">
            <Link href="#">
              <button className="btn btn-primary w-48 text-base font-medium capitalize">
                Apply
              </button>
            </Link>
            <Link href="#">
              <button className="btn btn-primary w-48 border-none bg-zinc-700 text-base font-medium capitalize hover:bg-zinc-800">
                FAQ
              </button>
            </Link>
          </div>
        </main>
        <footer className="absolute right-0 bottom-0 p-5 md:absolute md:bottom-0">
          <SocialButtons />
        </footer>
      </div>
    </>
  );
};

export default Welcome;
