const ANSWER_RESTRICTION_IDS = [
  "string",
  "string_nullable",
  "string_255",
  "string_255_nullable",
  "string_150",
  "string_150_nullable",
  "long_answer_150",
  "url_nullable",
  "phone_number",
  "string_255_array",
  "boolean",
  "date",
  "date_nullable",
  "positive_number",
  "tshirt_size",
  "workshop_array",
  "hacker_skills",
  "gender",
] as const;
export type AnswerRestrictionId = (typeof ANSWER_RESTRICTION_IDS)[number];
